### ISSUE TITLE
Hi, Is the proposal still in development

### ISSUE THREAD

**Issue by Runner-2019** [dietmarkuehl/kuhllib#6]

**Comment by dietmarkuehl** [comment]
I’m not sure which proposal exactly you are referring to. However, assuming you refer to http://wg21.link/P2762 and the respective implementation in this repo: yes, that is still active! I expect to have an updated version of the paper for the Varna meeting (as this is soare time work it currently doesn’t move as I need to progress with my conference presentation).

**Comment by Runner-2019** [comment]
That's really nice. I am really looking forward to reading your P2762R2 paper.
