### ISSUE TITLE
some critical pieces are missing

### ISSUE THREAD

**Issue by deepgrace** [dietmarkuehl/kuhllib#8]
This library is well written, it's almost a full featured sender / receiver based network library, great work!
Would you please add the implementations of the following critical pieces:

1
`async_read` sender, is very easy to add, just copy and replace `async_write` with `async_read` in file  `async_write.hpp` to a new file `async_read.hpp`

2
the definitions of timer's member functions `cancel`, `cancel_one`, `expires_at` and `expires_after` in file [basic_waitable_timer.hpp](https://github.com/dietmarkuehl/kuhllib/blob/main/src/nstd/timer/basic_waitable_timer.hpp)

3
error reporting for `async_read` and  `async_write`:
```cpp
void client_session::do_read_message()
{
    EX::start_detached(
    EX::just()
    | EX::let_value([this]
      {   
          return EX::on(scheduler,
                 NN::async_read(socket, NN::buffer(buff,  size))
                 | EX::then([this]<typename E>(const E& error_code)
                   {
                       if (!error_code)
                            on_read_message();
                   }));
      }));
}
```
the **`const E& error_code`** part is what i'm hoping to see, without this, we can just coding it with `upon_error` like this:
```cpp
void server_session::do_write()
{
    EX::start_detached(
    EX::just()
    | EX::let_value([this]
      {
          return EX::on(scheduler,
                 NN::async_write(socket, NN::buffer(buff,  size))
                 | EX::then([this]
                   {
                       on_write();
                   })
                 | EX::upon_error([this]<typename T>(const T& t)
                   {
                       if constexpr(requires { t.message(); })
                           close(t);
                   }));
      }));
}
```

4
remove or comment out ::std::terminate() at line 148 in file [start_detached.hpp](https://github.com/dietmarkuehl/kuhllib/blob/main/src/nstd/execution/start_detached.hpp)
It's not reasonable to terminate the whole program just because of some errors occurred.

Looking forward to see your reply, thanks!

**Comment by dietmarkuehl** [comment]
Thanks for your comments/issues (if they were issue the could be addressed individually).

1. The first item (add `async_read`) without much tests is reasonably easy to do: I just commited that change.
2. Although my current implementation includes `basic_waitable_timer` I'm not sure that'll stay: while ASIO requires(~d?) an object to cancel operations, the same isn't true for sender/receiver: cancellation is automatically hooked up and no separate object is needed (see 3.5 of [my networking proposal](http://wg21.link/p2762r0)). Correspondingly, I'm not too keen to adding that. Of course, that isn't really a good excuse for not having a corresponding set of timers, though (my primary excuse is that timers isn't currently my main focus: there are various changes needed for the actual networking operations).
3. Similar to the timer changes, the error handling is also discussed a bit in [my networking proposal](http://wg21.link/p2762r0) (in section 3.2). Looking at the notes from the discussion, it seems I neglected to properly discuss this point at the previous meeting: there were lots of other aspects discussed at a more general level. The key takeaway from the discussion was [potentially] fold partial successes into the error channel (and a separate design enhancements of sender/receivers, notably a progress notification "`set_next`" may yield a nicer approach for dealing with partial success).

   However, based on prior discussions in smaller groups it is quite clear that errors _should *not*_ be factored into the value channel! The primary reason is that algorithms need to be able to distinguish failures. While that may be a bit more cumbersome on direct use of the low-level senders, it is likely to provide for more advanced algorithms.

    Users wishing to simplify their uses or use a different error mechanism, e.g., within the context of coroutine, can just repackage the senders into a new custom sender. In many cases the custom alternative interface can actually be a generic algorithm, i.e., there isn't much operational code to write: it just requires a definition of some `constexpr` objects once the generic algorithm is written.
5. The last one (`start_detach` shouldn't `std::terminate()`) is the easiest one: from a semantic point of view it is equivalent to an exception escaping from a thread or `main()`: in both cases `std::terminate()` is called. My implementation just follows the [[current] specification](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2023/p2300r6.html#spec-execution.senders.consumers.start_detached) which has `start_detached` call `std::terminate` if `set_error` gets called. Whether that survives into the standard is unclear, though: there are questions on whether `start_detached` should be removed from the [std::execution proposal](http://wg21.link/p2300).
